name: YNOV pipeline CI/CD

on:
  push:
  workflow_dispatch:
    inputs:
      server-python-version:
        type: choice
        description: Which Python version will be runned on production server?
        options:
        - 3.9
        - 3.10
        - 3.11
        required: true

stages:
  - build
  - test
  - deploy
  - notify
  
build-job:
  runs-on: ubuntu-latest
  stage: build
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Lint with black
      run: |
        black . --check


test-job:
  runs-on: ubuntu-latest
  stage: test
  strategy:
    matrix:
      python-version: ["3.9", "3.10", "3.11"]
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Test with Pytest
      run: |
        pytest --doctest-modules --ignore=main.py

deploy-job:
  runs-on: ubuntu-latest
  stage: deploy
  steps:
    - name: MEP
      run: echo "MEP on server"

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Test if website is up 🚀
      run: |
        pip install requests
        python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"
  allow_failure: true

notify-job:
  runs-on: ubuntu-latest
  stage: notify
  steps: 
    - name: SLACK
      run: echo "Pipeline run"